import { db } from '@/lib/db';
import { generateSalt, hashToken } from '@/lib/auth';
import { uiAuth } from '@/lib/schema';
import { eq, sql } from 'drizzle-orm';

export const ADMIN_TOKEN_ENV = 'PCP_ADMIN_TOKEN';
export const DEPLOYMENT_GUIDE_URL = 'https://nesbitt-bot.github.io/personal-context-protocol/deployment-vercel-neon.html';
const MIN_ADMIN_TOKEN_LENGTH = 32;

export class AdminTokenConfigurationError extends Error {
  code = 'INVALID_ADMIN_TOKEN' as const;
  docsUrl = DEPLOYMENT_GUIDE_URL;
}

export function configuredAdminToken() {
  return process.env[ADMIN_TOKEN_ENV]?.trim() || '';
}

export function validateAdminToken(token: string) {
  if (token.trim().length < MIN_ADMIN_TOKEN_LENGTH) {
    return `admin token must be at least ${MIN_ADMIN_TOKEN_LENGTH} characters`;
  }
  return '';
}

export function configuredAdminTokenValidationError() {
  const token = configuredAdminToken();
  return token ? validateAdminToken(token) : '';
}

export function assertConfiguredAdminTokenIsValid() {
  const validationError = configuredAdminTokenValidationError();
  if (validationError) {
    throw new AdminTokenConfigurationError(validationError);
  }
}

export function generatedAdminTokenMessage() {
  return 'No PCP_ADMIN_TOKEN was configured, so PCP generated a first-login admin token. It is shown once here and printed once in server logs. Log in with it, then change it immediately in Settings so the real credential is never visible in logs.';
}

/**
 * This is the one intentional plaintext-token log path. It only prints tokens
 * generated by PCP for zero-config first login, never a user-supplied token.
 */
export function logGeneratedAdminToken(token: string, reason: string) {
  console.log('\n' + '='.repeat(70));
  console.log('  personal-context-protocol generated first-login admin token');
  console.log('='.repeat(70));
  console.log(`Reason: ${reason}`);
  console.log(`Admin token: ${token}`);
  console.log('Log in with this token, then change it immediately in Settings.');
  console.log('After rotation, the real admin credential will not be printed in logs.');
  console.log(`${'='.repeat(70)}\n`);
}

/**
 * Returns whether the database already has the single admin credential row.
 */
export async function adminCredentialExists() {
  const [stored] = await db
    .select({ id: uiAuth.id })
    .from(uiAuth)
    .where(eq(uiAuth.id, 'ui_1'))
    .limit(1);

  return Boolean(stored);
}

/**
 * Stores a UI/admin token as a salted hash. The plaintext token is accepted only
 * at the API/env boundary and is never returned or logged by this helper.
 */
export async function storeAdminToken(token: string) {
  const validationError = validateAdminToken(token);
  if (validationError) {
    throw new Error(validationError);
  }

  const salt = generateSalt();
  const tokenHash = await hashToken(token.trim(), salt);

  await db.execute(sql`
    INSERT INTO ui_auth (id, token_hash, salt, created_at, updated_at)
    VALUES ('ui_1', ${tokenHash}, ${salt}, now(), now())
    ON CONFLICT (id) DO UPDATE SET
      token_hash = EXCLUDED.token_hash,
      salt = EXCLUDED.salt,
      updated_at = now()
  `);
}

/**
 * Applies a manually configured deployment admin token to the database. This is
 * the safe recovery path for a lost UI token: set PCP_ADMIN_TOKEN in Vercel and
 * redeploy, then log in with that value.
 */
export async function reconcileConfiguredAdminToken() {
  assertConfiguredAdminTokenIsValid();
  const token = configuredAdminToken();
  if (!token) {
    return { configured: false, applied: false };
  }

  await storeAdminToken(token);
  return { configured: true, applied: true };
}
