import { pgTable, text, timestamp, boolean, integer, jsonb } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { APP_VERSION } from './version';

// App instance (single row)
export const appInstance = pgTable('app_instance', {
  id: text('id').primaryKey().$default(() => 'instance_1'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  initializedAt: timestamp('initialized_at', { withTimezone: true }),
  version: text('version').notNull().default(APP_VERSION),
});

// UI admin token. `source` records who owns the credential:
//   'deploy' — auto-generated by deploy initialization (rotated each deploy)
//   'env'    — loaded from PCP_ADMIN_TOKEN (the env var owns it)
//   'user'   — set by the admin in Settings (never auto-rotated)
export const uiAuth = pgTable('ui_auth', {
  id: text('id').primaryKey().$default(() => 'ui_1'),
  tokenHash: text('token_hash').notNull(),
  salt: text('salt').notNull(),
  source: text('source', { enum: ['deploy', 'env', 'user'] }).notNull().default('deploy'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
});

// Topics
export const topics = pgTable('topics', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description'),
  archived: boolean('archived').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// Sessions. `topicId` is nullable: a session may be uncategorized (no topic).
// `public` exposes a read-only view without the admin UI token.
export const sessions = pgTable('sessions', {
  id: text('id').primaryKey(),
  topicId: text('topic_id').references(() => topics.id),
  title: text('title').notNull(),
  // Recording mode the agent is told to honor: 'wild' (default) lets the agent
  // redact secrets it judges unsafe; 'exact' asks for verbatim recording
  // (including credentials) for faithful task migration.
  mode: text('mode', { enum: ['wild', 'exact'] }).notNull().default('wild'),
  public: boolean('public').notNull().default(false),
  archived: boolean('archived').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  lastMessageAt: timestamp('last_message_at', { withTimezone: true }),
});

// Session tokens
export const sessionTokens = pgTable('session_tokens', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => sessions.id),
  tokenHash: text('token_hash').notNull(),
  salt: text('salt').notNull(),
  name: text('name').notNull(),
  canRenameSession: boolean('can_rename_session').notNull().default(false),
  revoked: boolean('revoked').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  tokenPrefix: text('token_prefix'), // First 16 chars for quick lookup
});

// Scoped tokens: the unified token layer managed by the global token manager.
// `scope` bounds the token ('global' = full, 'folder' = one topic, 'session' =
// one session); `permissionsJson` carries fine-grained flags (see scoped-token.ts).
export const scopedTokens = pgTable('scoped_tokens', {
  id: text('id').primaryKey(),
  tokenHash: text('token_hash').notNull(),
  salt: text('salt').notNull(),
  tokenPrefix: text('token_prefix'),
  name: text('name').notNull(),
  scope: text('scope', { enum: ['global', 'folder', 'session'] }).notNull(),
  folderId: text('folder_id').references(() => topics.id),
  sessionId: text('session_id').references(() => sessions.id),
  permissionsJson: jsonb('permissions_json').default({}),
  revoked: boolean('revoked').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
});

// Session-to-session links: an undirected, optionally labelled relationship so
// a model (or human) can connect related conversations (e.g. a DSH session and
// the PCP session that records it). `sessionA`/`sessionB` are stored in a
// normalized order (A <= B) by the write path.
export const sessionLinks = pgTable('session_links', {
  id: text('id').primaryKey(),
  sessionA: text('session_a').notNull().references(() => sessions.id),
  sessionB: text('session_b').notNull().references(() => sessions.id),
  label: text('label'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// Messages
export const messages = pgTable('messages', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => sessions.id),
  // Denormalized from the session; null when the session has no topic.
  topicId: text('topic_id').references(() => topics.id),
  ordinal: integer('ordinal').notNull(),
  role: text('role', { enum: ['user', 'assistant', 'system', 'tool', 'correction'] }).notNull(),
  content: text('content').notNull(),
  contentType: text('content_type', { enum: ['text', 'markdown', 'json'] }).notNull().default('markdown'),
  provider: text('provider'),
  BaseModel: text('base_model'),
  providerTimestamp: timestamp('provider_timestamp', { withTimezone: true }),
  observedAt: timestamp('observed_at', { withTimezone: true }).notNull(),
  sourceJson: jsonb('source_json'),
  metadataJson: jsonb('metadata_json').default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// Compactions: durable session summaries stored alongside (never replacing)
// raw messages, for when full message upload is impossible.
export const compactions = pgTable('compactions', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => sessions.id),
  summary: text('summary').notNull(),
  timelineJson: jsonb('timeline_json'),
  decisionsJson: jsonb('decisions_json'),
  requirementsJson: jsonb('requirements_json'),
  openQuestionsJson: jsonb('open_questions_json'),
  artifactsJson: jsonb('artifacts_json'),
  warningsJson: jsonb('warnings_json'),
  provider: text('provider'),
  baseModel: text('base_model'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  metadataJson: jsonb('metadata_json').default({}),
});

// Events
export const events = pgTable('events', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').references(() => sessions.id),
  topicId: text('topic_id').references(() => topics.id),
  action: text('action').notNull(),
  actor: text('actor').notNull(),
  detailsJson: jsonb('details_json').default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// Schema migrations
export const schemaMigrations = pgTable('schema_migrations', {
  version: text('version').primaryKey(),
  appliedAt: timestamp('applied_at', { withTimezone: true }).notNull().defaultNow(),
  checksum: text('checksum'),
});
